version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dependabot
  ignore:
  - dependency-name: MongoDB.Driver
    versions:
    - 2.11.6
    - 2.12.0
    - 2.12.1
  - dependency-name: FakeItEasy
    versions:
    - 6.2.1
    - 7.0.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
  - dependency-name: Unity
    versions:
    - 5.11.9
