<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <PackageId>BE.CQRS.Mapping</PackageId>
    <PackageProjectUrl>https://github.com/BoasE/BE.CQRS</PackageProjectUrl>
    <PackageReleaseNotes>.net 10</PackageReleaseNotes>
    <PackageVersion>0.100.0-alpha</PackageVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>BoasE</Authors>
    <Company>BoasE</Company>
    <Description>AutoMapper integration for BE.CQRS projections and DTO mapping.</Description>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="BE.CQRS.Domain" Version="0.100.0-alpha" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Domain\Domain\Domain.csproj" />
  </ItemGroup>

</Project>